"""
app.py — Streamlit dashboard for deviation visualization.
Run with: streamlit run dashboard/app.py
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import numpy as np

st.set_page_config(page_title="Digital Twin — Deviation Monitor", layout="wide")
st.title("Digital Twin — Construction Deviation Monitor")

# ── Sidebar ──────────────────────────────────────────────────────────────────
st.sidebar.header("Load Results")
uploaded = st.sidebar.file_uploader("Upload deviation_report.csv", type="csv")
threshold = st.sidebar.slider("Alert threshold (m)", 0.01, 0.5, 0.05, 0.01)

# ── Main ─────────────────────────────────────────────────────────────────────
if uploaded is None:
    st.info("Upload a deviation report CSV generated by `pipeline/deviation.py` to get started.")
    st.stop()

df = pd.read_csv(uploaded)
required = {"x", "y", "z", "deviation_m"}
if not required.issubset(df.columns):
    st.error(f"CSV must contain columns: {required}")
    st.stop()

df["alert"] = df["deviation_m"] > threshold

# ── KPI row ───────────────────────────────────────────────────────────────────
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total points", f"{len(df):,}")
col2.metric("Mean deviation", f"{df['deviation_m'].mean():.3f} m")
col3.metric("Max deviation", f"{df['deviation_m'].max():.3f} m")
col4.metric("Alert points", f"{df['alert'].sum():,}", delta=f"{100*df['alert'].mean():.1f}%", delta_color="inverse")

st.divider()

# ── 3D scatter ────────────────────────────────────────────────────────────────
st.subheader("3D Deviation Heatmap")

sample = df.sample(min(50_000, len(df)), random_state=42)

fig = go.Figure(go.Scatter3d(
    x=sample["x"], y=sample["y"], z=sample["z"],
    mode="markers",
    marker=dict(
        size=2,
        color=sample["deviation_m"],
        colorscale="RdYlGn_r",
        cmin=0,
        cmax=threshold * 4,
        colorbar=dict(title="Deviation (m)"),
        opacity=0.8,
    ),
    text=sample["deviation_m"].round(4).astype(str) + " m",
    hovertemplate="x=%{x:.2f} y=%{y:.2f} z=%{z:.2f}<br>dev=%{text}<extra></extra>",
))
fig.update_layout(
    scene=dict(xaxis_title="X (m)", yaxis_title="Y (m)", zaxis_title="Z (m)"),
    height=600, margin=dict(l=0, r=0, b=0, t=0),
)
st.plotly_chart(fig, use_container_width=True)

# ── Histogram ─────────────────────────────────────────────────────────────────
st.subheader("Deviation Distribution")
hist_fig = go.Figure(go.Histogram(
    x=df["deviation_m"], nbinsx=80,
    marker_color="steelblue", opacity=0.8,
))
hist_fig.add_vline(x=threshold, line_dash="dash", line_color="red",
                   annotation_text=f"Threshold {threshold} m")
hist_fig.update_layout(xaxis_title="Deviation (m)", yaxis_title="Point count", height=300)
st.plotly_chart(hist_fig, use_container_width=True)

# ── Alert table ───────────────────────────────────────────────────────────────
st.subheader("Alert Points")
alerts = df[df["alert"]].sort_values("deviation_m", ascending=False)
st.dataframe(alerts.head(500), use_container_width=True)
